apiVersion: v1
kind: Service
metadata:
  name: {{ include "gendeck.fullname" . }}-backend
  labels:
    {{- include "gendeck.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gendeck.backend.selectorLabels" . | nindent 4 }}
